import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";

import Banner from "./Banner";
import Services from "./Services";
import Team from "./Team";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zolvebiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <Services />
      <Team />
    </div>
  );
}
